#!/usr/bin/env bash

# USE:
#
#   * cb                  # outputs the content of the clipboard
#   * fortune | cb        # Pipes fortune's output into the clipboard
#   * cb --force-paste    # forces cb to start in 'paste' mode
#   * cb --listen         # starts a clipboard daemon -- handy when trying to
#                         # update the clipboard from a remote ssh session

CB_REMOTE_PORT=${CB_REMOTE_PORT:-${LC_CB_REMOTE_PORT:-5556}}
CB_REMOTE_PASTE_REQUEST_TOKEN=AKDJF8U4389HSDHF3H9RH39FJSKDHFJH983QR98HAUFHA

listen() {
    echo "Listening on port ${CB_REMOTE_PORT}..."
    while (true); do
        python3 <<END
from __future__ import print_function
import socket, subprocess

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.bind(('localhost', ${CB_REMOTE_PORT}))
s.listen(1)
remote, _ = s.accept()
input = b''
while True:
    data = remote.recv(1024)
    if not data:
        break
    input += data
if input == b'${CB_REMOTE_PASTE_REQUEST_TOKEN}':
    clipboard = subprocess.check_output(['$0',  '--force-paste'])
    remote.sendall(clipboard)
    print('Pasted')
    print(clipboard)
else:
    process = subprocess.Popen(['$0'], stdin=subprocess.PIPE)
    process.communicate(input)
    process.wait()
    print('Copied')
    print(input)
remote.close()
s.close()
END
        if [ $? -ne 0 ]; then
            break
        fi
    done
}

paste() {
    if env | grep --quiet -F SSH_TTY; then
        echo -n ${CB_REMOTE_PASTE_REQUEST_TOKEN} | remote
    elif [ -e /dev/clipboard ]; then
        cat /dev/clipboard
    elif hash powershell.exe 2>/dev/null; then
        powershell.exe -NoProfile -Command "[Console]::OutputEncoding = [System.Text.Encoding]::UTF8; Get-Clipboard"
    elif hash xsel 2>/dev/null; then
        xsel --clipboard --output
    else
        pbpaste
    fi
}

copy() {
    local input
    input=$(cat)
    if [ -n "${CB_OSC52:-${LC_CB_OSC52:-}}" ] && printf '%s' "$input" | osc52_copy; then
        : # do nothing... it would already have been copied
    elif env | grep --quiet -F SSH_TTY; then
        printf '%s' "$input" | remote
    elif [ -e /dev/clipboard ]; then
        printf '%s' "$input" > /dev/clipboard
    elif hash clip.exe 2>/dev/null; then
        printf '%s' "$input" | clip.exe
    elif hash xsel 2>/dev/null; then
        printf '%s' "$input" | xsel --clipboard --input
    else
        printf '%s' "$input" | pbcopy
    fi
}

remote() {
    if hash socat 2>/dev/null; then
        socat - TCP:localhost:${CB_REMOTE_PORT},shut-down
    else
        nc -N localhost ${CB_REMOTE_PORT}
    fi
}

osc52_copy() {
    # Check if we actually have a TTY to write to.
    # If /dev/tty isn't available, we skip OSC52 and return a 
    # non-zero status so 'copy' can try the next method.
    if ! [ -w /dev/tty ]; then
        return 1
    fi

    data=$(base64 | tr -d '\n')
    if [ -n "$TMUX" ]; then
        # DCS passthrough for tmux
        printf '\033Ptmux;\033\033]52;c;%s\a\033\\' "$data" > /dev/tty
    else
        printf '\033]52;c;%s\a' "$data" > /dev/tty
    fi
}

if [ "$1" = "--listen" ]; then
    listen
elif [ "$1" = "--force-paste" ]; then
    paste
else
    test -t 0 && paste || copy
fi
