#!/usr/bin/env bash

# USE:
# 
#   * cb                  # outputs the content of the clipboard
#   * fortune | cb        # Pipes fortune's output into the clipboard
#   * cb --force-paste    # forces cb to start in 'paste' mode
#   * cb --listen         # starts a clipboard daemon -- handy when trying to
#                         # update the clipboard from a remote ssh session

CB_REMOTE_PORT=${CB_REMOTE_PORT:-5556}
CB_REMOTE_PASTE_REQUEST_TOKEN=AKDJF8U4389HSDHF3H9RH39FJSKDHFJH983QR98HAUFHA

listen() {
    echo "Listening on port ${CB_REMOTE_PORT}..."
    while (true); do
        python <<END
import socket, subprocess

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.bind(('localhost', ${CB_REMOTE_PORT}))
s.listen(1)
remote, _ = s.accept()
input = ''
while True:
    data = remote.recv(1024)
    if not data:
        break
    input += data
if input == '${CB_REMOTE_PASTE_REQUEST_TOKEN}':
    clipboard = subprocess.check_output(['$0',  '--force-paste'])
    remote.sendall(clipboard)
    print 'Pasted'
    print clipboard
else:
    process = subprocess.Popen(['$0'], stdin=subprocess.PIPE)
    process.communicate(input)
    process.poll()
    print 'Copied'
    print input
remote.close()
s.close()
END
        if [ $? -ne 0 ]; then
            break
        fi
    done
}

paste() {
    if env | grep --quiet -F SSH_TTY; then
        echo -n ${CB_REMOTE_PASTE_REQUEST_TOKEN} | nc localhost ${CB_REMOTE_PORT}
    elif [ -e /dev/clipboard ]; then
        getclip
    else
        pbpaste
    fi
}

copy() {
    if env | grep --quiet -F SSH_TTY; then
        nc localhost ${CB_REMOTE_PORT}
    elif [ -e /dev/clipboard ]; then
        putclip
    else
        pbcopy
    fi
}


if [ "$1" = "--listen" ]; then
    listen
elif [ "$1" = "--force-paste" ]; then
    paste
else
    test -t 0 && paste || copy
    fi
